apps_compose_path: "{{ apps_root_path }}/docker-compose.yml"
apps_data_path: "{{ apps_root_path }}/data"
consul_config_path: "{{ apps_root_path }}/consul/config"
hostnames: "{{ groups['all'] | map('extract',hostvars,'inventory_hostname') | join(',') }}"
nginx_path: "nginx/sites/"
aws_configs_path: ".aws/"
list_ip: "{{ list_ip.stdout }}"
list_port: "{{ port_result.stdout_lines }}"
busy_ports: "{{ docker_ports.stdout }}"