---
#================docker install=====================#
- name: Package Installer For Docker
  package:
    name: docker
    state: present
- name: Package Installer For Python3
  package:
    name: python3
    state: present
- name: Start service docker
  service:
    name: docker
    state: started
- name: Install unzip
  become: yes
  package:
    name: unzip
    state: latest
- name: Install jq
  become: yes
  package:
    name: jq
    state: latest
- name: Install pbzip2
  become: yes
  package:
    name: pbzip2
    state: latest
  ignore_errors: yes
- name: Install net-tools package
  become: yes
  package:
    name: net-tools
    state: latest
  ignore_errors: yes
- name: Install python3-pip package
  become: yes
  package:
    name: python3-pip
    state: latest
  ignore_errors: yes
- name: Install python3-pip package
  become: yes
  package:
    name: python3-pip
    state: latest
  ignore_errors: yes
- name: Update pip if it possible
  pip:
    name: pip
    executable: pip-3
    state: latest
  ignore_errors: yes

- name: Install Docker Module for Python
  pip:
    name: docker==4.4.4
    executable: pip-3
    state: present

- name: Install Docker-compose for Python
  pip:
    name: docker-compose
    executable: pip-3
- name: pip install yaml module
  pip:
    name:
      - PyYAML==5.1
      - netaddr
    executable: pip-3
    extra_args: --ignore-installed

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download awscliv2 installer.
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "{{ executable_temp_dir }}"
    remote_src: true
    creates: '{{ executable_temp_dir }}/aws'
    mode: 0755

- name: Run the installer.
  command:
  args:
    cmd: "{{ executable_temp_dir }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
